# Generated by Django 5.1.7 on 2025-04-03 19:46

import dummy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default=dummy.models.generate_serial, max_length=20, unique=True)),
                ('mac', models.CharField(default=dummy.models.generate_mac, max_length=17, unique=True)),
                ('fw_info', models.CharField(default='AIROS-1.0.1-BUILD_23092024', max_length=50)),
                ('hw_name', models.CharField(default='MTK7621', max_length=50)),
                ('hw_version', models.CharField(default='1.0', max_length=10)),
                ('mgmt_ip', models.GenericIPAddressField(default=dummy.models.generate_ip)),
                ('egress_ip', models.GenericIPAddressField(default=dummy.models.generate_ip)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
