# Generated by Django 5.1.7 on 2025-04-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('fw_info', models.CharField(max_length=100)),
                ('hw_name', models.CharField(max_length=100)),
                ('hw_version', models.CharField(max_length=100)),
                ('mgmt_ip', models.GenericIPAddressField()),
                ('egress_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
