# Generated by Django 5.1.7 on 2025-04-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_registereddevice_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('fw_info', models.CharField(max_length=255)),
                ('hw_name', models.CharField(max_length=255)),
                ('hw_version', models.CharField(max_length=255)),
                ('mgmt_ip', models.GenericIPAddressField()),
                ('egress_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.DeleteModel(
            name='RegisteredDevice',
        ),
    ]
