# Generated by Django 5.1.7 on 2025-04-22 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_device_delete_registereddevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='fw_info',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='hw_name',
            new_name='device_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='egress_ip',
        ),
        migrations.RemoveField(
            model_name='device',
            name='hw_version',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mgmt_ip',
        ),
        migrations.RemoveField(
            model_name='device',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
