# Generated by Django 5.2 on 2025-05-28 07:17

import cloud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_rename_fw_info_device_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default=cloud.models.generate_serial, max_length=20)),
                ('mac', models.CharField(default=cloud.models.generate_mac, max_length=100)),
                ('fw_info', models.CharField(default='AIROS-1.0.1-BUILD_23092024', max_length=50)),
                ('hw_name', models.CharField(default='MTK7621', max_length=50)),
                ('hw_version', models.CharField(default='1.0', max_length=10)),
                ('mgmt_ip', models.GenericIPAddressField(default=cloud.models.generate_ip)),
                ('egress_ip', models.GenericIPAddressField(default=cloud.models.generate_ip)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
        migrations.AddField(
            model_name='device',
            name='egress_ip',
            field=models.GenericIPAddressField(default=cloud.models.generate_ip),
        ),
        migrations.AddField(
            model_name='device',
            name='fw_info',
            field=models.CharField(default='AIROS-1.0.1-BUILD_23092024', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='hw_name',
            field=models.CharField(default='MTK7621', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='hw_version',
            field=models.CharField(default='1.0', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='mac',
            field=models.CharField(default=cloud.models.generate_mac, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='mgmt_ip',
            field=models.GenericIPAddressField(default=cloud.models.generate_ip),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default=cloud.models.generate_serial, max_length=20),
        ),
    ]
